AllCops:
  NewCops: enable
Naming/MethodParameterName:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
